### ISSUE TITLE
animate a dumbbell and the person, who moves it, simultaneously (with params/morphs)

### ISSUE THREAD

**Issue by testingjava** [acidbubbles/vam-timeline#17]
Hi acidbubbles,

This is really a great project / plugin for VAM 1.x
A Timeline and keyframe animation are missing in VAM 1.x so far.
I think, that some users hope, that it will be part of VAM 2.x. but they will be very happy about this plugin.

I don't know github (and vam) very well, so i hope its ok to write this here by opening a new issue.

I would like to animate an atom like a dumbbell (imported as a custom unity asset) and to animate the person, who moves the dumbbell at the same time.

The suggested way seems to be to animate the dumbbell and to link the right or left hand (physics link) to the dumbbell-asset/atom (with "link position and rotation spring" in the pysics tab at the highest value of 100.000). This way the hand follows the dumbbell without histeresis. To move the hand and to link the dumbbell is not as good as the other way.

With your plugin i animated the dumbbell (after adding VamTimeline.LinkedAnimation.cs to it) and linked the dumbbell animation (in animation settings) to another animation created as an animation pattern of the same length ( available in plugin release 1.7.4). I saw, that you removed this option in 1.8 and that you thought about bringing this feature back in a future release.

My question is:
What is the best way to play two animations of two different atoms at the same time (simultaneous). At least one animation (of the person) should contain animation of params like morphs. Animation pattern don't have this option as far as i know. But your plugin has it.
So is it possible that one anim01 of one atom (with plugin connected) can trigger or be linked to another anim02 of another atim (with plugin connected).

greetings

Edit: Animations of two different atoms can be played simultaneously with an animation trigger.

**Comment by acidbubbles** [comment]
You can use VamTimeline.Controller.cslist on a SimpleSign, and link multiple atoms with animations on them. This was built to synchronize multiple animations. But I did bring back AnimationPattern links, so you can download a more recent version if you want!
