### ISSUE TITLE
Scrubbing to end of a non-looping animation does not land on keyframe.

### ISSUE THREAD

**Issue by VamDazzler** [acidbubbles/vam-timeline#27]

**Comment by acidbubbles** [comment]
I'm not able to reproduce this, can you provide specific instructions and provide the version you're using?

**Comment by acidbubbles** [comment]
AH wait I think I see what you mean, it actually selects the _first_ keyframe. I'll check this out.

**Comment by VamDazzler** [comment]
Unfortunately, no.  It's just a state that it sometimes gets in where scrubbing to the end doesn't seem to get all the way to the end; I can hit "next frame" and it will move to the frame I should have been sitting on.  I remember it most recently happening on .19.var.

It could be a strange byproduct of my using Vam through remote desktop whenever I'm in desktop mode, though; there are some other strange UI behaviours I have to deal with; so if its irreproducable, feel free to close.
