### ISSUE TITLE
Cannot copy end frame of a non-looping animation.

### ISSUE THREAD

**Issue by VamDazzler** [acidbubbles/vam-timeline#28]
Very very useful for re-syncing moved targets for the first frame of a followup looping animation.

**Comment by acidbubbles** [comment]
Same as #27 - I cannot reproduce, I just tried and it worked. If you can provide the version and how to reproduce, it would be helpful!

**Comment by acidbubbles** [comment]
Ah, I figured it out :D Will fix!
