### ISSUE TITLE
Animatiom won't play on import.

### ISSUE THREAD

**Issue by smokeyred77** [acidbubbles/vam-timeline#30]
I made a few animations for 1 scene and exported them as a json and they worked great.  When I started a new scene and added the plugin I wanted to import those animations which I did.  But when I press the play button it says its playing but nothing happens. If I hit stop and slide the scrubber the whole animation is in there but when play is pressed it says it plays but again nothing happens, the scrubber does not move at all. And If i make a new animation that one works fine and when it moves to the loaded animation it just stops again. any Ideas?

**Comment by acidbubbles** [comment]
Do you have any controllers (including the person atom itself) that has any parenting?

**Comment by smokeyred77** [comment]
I figured It out. Had nothing parented but on the original scene all joints were on, and on the new scene only the Key joints were on and all others were off. I'll just have to set all on for all animations or come up with a standard of ones I want on. Thanks for your help and this wonderful Plugin.

**Comment by acidbubbles** [comment]
Yeah I need to think this through. I thought of recording the initial controllers position, but if you have multiple animations it may not make much sense to have import screw up other animations. I may end up doing this anyway eventually.

**Comment by acidbubbles** [comment]
The latest version now saves all initial controller positions, this should help :)
