### ISSUE TITLE
Morphs not animating in 1.20?

### ISSUE THREAD

**Issue by HeLL-HoRZe** [acidbubbles/vam-timeline#33]
Hi, I am not sure if I am doing something wrong but I will do the best I can to describe the issue, what works and what doesn't.

Vam Ver 1.20

What doesn't seem to animate are the morphs in Vam Ver 1.20

The timeline still allows you to pick the float param, but when you use the Vam UI to manipulate the morph you have selected. it has no bearing on the timeline at all. Moving the morph's slider isn't detected by the timeline it seems.

**Comment by Psy185** [comment]
If I understand your issue correctly, you don't have to change the morph via Vam, but the timeline plugin. Add the morph param to the animation and choose the tab param. There you will see the slider which is saved in each frame of the animation.

If I misunderstood, I am sorry. I'm fairly new to Vam and this plugin...

**Comment by acidbubbles** [comment]
For now there's already a discussion in progress in the #bugs channel on Discord, to avoid having parallel discussions I'll close this here. If there's a bug, I'll re-open!
