### ISSUE TITLE
"Random Group Weight" not Restoring on Scene Load

### ISSUE THREAD

**Issue by d8ahazard** [acidbubbles/vam-timeline#46]
Perhaps I'm just using the param wrong, but it seems as if the Random Group Weight param is not being saved/reloaded properly.

I have an atom with an "appear" and "disappear" animation which moves the control in/out of the scene, as well as several other looping animations that I'd like to have play randomly until the disappear animation is triggered.

I can go into timeline, set the RGW for the appear/disappear animations to zero, and then the random loops cycle fine.

But, if I then save and reload the scene, the RGW values are set back to 1, and instead of nice smooth randomization, the atom randomly flies in and out of the scene. Kinda entertaining, but not the desired behavior. :P

**Comment by acidbubbles** [comment]
Answered here: https://hub.virtamate.com/threads/timeline.94/page-17#post-55855 and Trello issue: https://trello.com/c/UjvLzPT9/541-timeline-randomize-weight-set-to-zero-will-load-as-being-one
