### ISSUE TITLE
Random group weight not save when at 0

### ISSUE THREAD

**Issue by TheTerribleFairy** [acidbubbles/vam-timeline#47]
As title says, whenever I set an animation random group weight to 0, it doesn't save the next time I load the scene. It will still save any other animation random group weight it they are anything other than 0. This is annoying because it forces me to put them all back to 0 again whenever I load my scene. It would be really nice if it could save it, thank you.

**Comment by acidbubbles** [comment]
Fixed :)

**Comment by TheTerribleFairy** [comment]
nice! Was it updated on the Hub? It is not showing me any update

**Comment by acidbubbles** [comment]
Yes: https://hub.virtamate.com/resources/timeline.94/updates

Note that the save file doesn't have to "0" so you'll have to set it on the next load, but the next save should be fine!
