### ISSUE TITLE
Multi Hero Pose Save.

### ISSUE THREAD

**Issue by s3intBeko** [acidbubbles/vam-timeline#53]
Hello i have same error.And i did many things to fix but no result.
i open new empty scene and add 2 atom and when i added to timeline to them when add second one its no more save current position.i guess i made something to broke it because it was working before do you have idea why it can be ? 
Note:actually i see that its not for multi atoms even for 1 can be same i open log but its shows nothing ..

**Comment by acidbubbles** [comment]
I just got to this issue (as you might guess, I have quite a few to run through) and I see you've closed it, and I don't see any code. Is there anything to know about the PR and why it was removed?
